version: '3.7'
services:
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  #   restart: always
  #   ports:
  #     - "9200:9200"
  #     # - "9300:9300"
  #   environment:
  #     discovery.type: single-node
  #   volumes:
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     discovery.type: single-node
  #     network.host: "0.0.0.0"
  #     bootstrap.memory_lock: "true"
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hingeto_supply_app_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
      - "16543:80"
    depends_on:
      - db
  redis:
    container_name: redis
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    # ports:
    #   - 27017:27017
    restart: always
  sidekiq:
    container_name: sidekiq
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hingeto_supply_app_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

      - SITE_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379/1
      - MONGODB_URI=mongodb://mongodb/hingeto_supply_app_development
      # - ELASTICSEARCH_URL=http://elasticsearch:9200
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    depends_on:
      - db
      - redis
      - mongodb
      # - elasticsearch
    volumes:
      - '../:/app'
  web:
    image: supply_web_new
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    restart: always
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hingeto_supply_app_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SITE_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379/1
      # - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MONGODB_URI=mongodb://mongodb/hingeto_supply_app_development
    depends_on:
      - db
      - redis
      - mongodb
      # - elasticsearch
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true
volumes:
  bundle_cache:
  mongodb_data_container:
  # elasticsearch:

# sudo chmod -R 777 admin
# docker-compose run --rm app bundle install
# sudo chmod -R 777 tmp/db/pg_stat_tmp/
# sudo chmod -R 777 tmp/db/pg_logical/replorigin_checkpoint
