---
:concurrency: <%= ENV["SIDEKIQ_CONCURRENCY"] || 1 %>
:queues:
  - ["default", 1]
  - ["critical", 10]
  - ["inventory_update", 5]
  - ["mailers", 5]
  - ["rollbar", 10]
  - ["import_action", 1]
  - ["shopify_export", 5]
  - ["shopify_import", 5]
  - ["shopify_product_import", 1]
  - ["shopify_webhook", 1]
  - ["shopify_cache", 1]
  - ["fetch_logo", 1]
  - ["webhook", 1]
  - ["images_import", 1]
  - ["bulk_product_uploads", 1]
  - ["bulk_product_downloads", 1]
  - ["imports", 1]
  - ["exports", 1]
  - ["csv_export", 1]
  - ["csv_import", 1]
  - ["product_import", 1]
  - ["order_export", 1]
